---
title: "Uber-Data-Analysis"
author: "Vinu Baburaj"
date: "`r Sys.Date()`"
output: html_document
---

```{r LoadPackages}
# Package names required for this project

packages <- c('ggplot2','tidyverse')

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Loading Packages
invisible(lapply(packages, library, character.only = TRUE))
```
```{r ReadCSV}
apr <- read_csv("dataset/uber-raw-data-apr14.csv")
may <- read_csv("dataset/uber-raw-data-may14.csv")
jun <- read_csv("dataset/uber-raw-data-jun14.csv")
jul <- read_csv("dataset/uber-raw-data-jul14.csv")
aug <- read_csv("dataset/uber-raw-data-aug14.csv")
sep <- read_csv("dataset/uber-raw-data-sep14.csv")
```


```{r CheckData}
head(apr)
head(may)
head(jun)
head(jul)
head(aug)
head(sep)
```

```{r JoinData}
data <- rbind(apr,may, jun, jul, aug, sep)
```


```{r}
head(data)
tail(data)
```


```{r}
data$`Date/Time` <- strptime(data$`Date/Time`, "%m/%d/%Y %H:%M:%S")
```

Separate column for Day, Month and Hour 

```{r}
data$Day <- as.numeric(format(data$`Date/Time`, format="%d"))
data$Month <- as.numeric(format(data$`Date/Time`, format="%m"))
data$Hour <- as.numeric(format(data$`Date/Time`, format="%H"))
```



